# Generated by Django 5.1.2 on 2024-10-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infographic", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="like_count",
            new_name="liked_count",
        ),
    ]
