# Generated by Django 5.1.2 on 2024-10-16 03:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infographic", "0002_rename_like_count_user_liked_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="insta_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_follower",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_following",
        ),
        migrations.RemoveField(
            model_name="user",
            name="liked_count",
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="크롤링 시간"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_account",
            field=models.CharField(
                default="no_account", max_length=30, verbose_name="사용자 인스타 아이디"
            ),
        ),
        migrations.CreateModel(
            name="Friendships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insta_id",
                    models.CharField(max_length=30, verbose_name="인스타 아이디"),
                ),
                (
                    "is_following",
                    models.BooleanField(default=False, verbose_name="팔로잉 여부"),
                ),
                (
                    "is_follower",
                    models.BooleanField(default=False, verbose_name="팔로워 여부"),
                ),
                (
                    "liked_count",
                    models.IntegerField(default=0, verbose_name="좋아요 횟수"),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships",
                        to="infographic.user",
                    ),
                ),
            ],
        ),
    ]
