# Generated by Django 5.1.2 on 2024-10-16 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infographic", "0003_remove_user_insta_id_remove_user_is_follower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendships",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="크롤링 시간"
            ),
        ),
    ]
